Mengambil Product ID skincare yang diminta oleh pengguna

In [1]:
import pandas as pd

age_range = "19 - 24"
skin_type = "Dry"
tag = "cream-1"

from connect import db 
cursor = db.cursor(dictionary=True)
sql = "SELECT products.*, count(reviews.id) as review_count from products join reviews on products.id=reviews.product_id  where tag=%s and reviews.age_range=%s and reviews.skin_type like %s group by products.id"
val = (tag,age_range,f"{skin_type}%")

cursor.execute(sql,val)
data = cursor.fetchall()
data = {row['id']: row for row in data}
pd.DataFrame(data.values())

,id,name,price,brand,tag,image,rating,description,category,review_count
0,259,Concentrated Ginseng Renewing Cream EX,1500000.00,Sulwhasoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.40,Sulwhasoo Concentrated Ginseng Renewing Cream ...,Moisturizer (Cream),9
1,72429,Lightening Day Cream,44000.00,Wardah,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.10,Wardah Lightening Day Cream Advanced Niacinami...,Moisturizer (Cream),77
2,697,Flawless White Visible Lightening Day Cream SP...,70000.00,Pond's,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.30,Pond’s Flawless White Visible Lightening Day C...,Moisturizer (Cream),16
3,951,Vitamin E Nourishing Night Cream,199000.00,The Body Shop,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.70,The Body Shop Vitamin E Nourishing Night Cream...,Moisturizer (Cream),29
4,606,Special Day Cream,5700.00,Viva Cosmetics,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.10,Viva Cosmetics Special Day Cream adalah krim p...,Moisturizer (Cream),2
...,...,...,...,...,...,...,...,...,...,...
451,98417,Bright Booster Perfecting Glow Face Cream,22700.00,Marina,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.20,Marina Expert White & Glow Perfecting Glow Fac...,Moisturizer (Cream),1
452,101812,Intense Luminous Barrier Moisturizer,69000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.60,Azarine Intense Luminous Barrier Moisturizer a...,Moisturizer (Cream),4
453,101813,Pure Radiance Barrier Moisturizer,69000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.30,Pelembab pagi dan malam untuk memudarkan bekas...,Moisturizer (Cream),1
454,98883,Gentle Forest Acne Night Cream,245000.00,Daily Cole,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.30,Daily Cole Gentle Forest Acne Night Cream meru...,Moisturizer (Cream),1
455,103058,Biome & Barrier Cream,149000.00,MS Glow,cream-1,https://image.femaledaily.com/dyn/360/images/p...,5.00,<p>MS GLOW Biome &amp; Barrier Cream merupakan...,Moisturizer (Cream),1

Menggabungkan inputan pengguna (product_id, skin_type, age_range)

In [2]:
data_input= []
product_id= list(data.keys())
for id in product_id:
    data_input.append({
        "product_id":id,
        "age_range":age_range,
        "skin_type":skin_type
    })
pd.DataFrame(data_input)

     product_id age_range skin_type
0           259   19 - 24       Dry
1         72429   19 - 24       Dry
2           697   19 - 24       Dry
3           951   19 - 24       Dry
4           606   19 - 24       Dry
..          ...       ...       ...
451       98417   19 - 24       Dry
452      101812   19 - 24       Dry
453      101813   19 - 24       Dry
454       98883   19 - 24       Dry
455      103058   19 - 24       Dry

[456 rows x 3 columns]

Melakukan one hot encoding untuk skin_type dan age_range

In [3]:
data_encoding = []
for inputan in data_input:
    data_encoding.append({
        'product_id': inputan["product_id"],
        'age_range_18 and Under': 1 if inputan["age_range"]== "18 and Under" else 0,
        'age_range_19 - 24': 1 if inputan["age_range"]== "19 - 24" else 0,
        'age_range_25 - 29': 1 if inputan["age_range"]== "25 - 29" else 0,
        'age_range_30 - 34': 1 if inputan["age_range"]== "30 - 34" else 0,
        'age_range_35 - 39': 1 if inputan["age_range"]== "35 - 39" else 0,
        'age_range_40 - 44': 1 if inputan["age_range"]== "40 - 44" else 0,
        'age_range_45 and Above': 1 if inputan["age_range"]== "45 and Above" else 0,
        'skin_type_Combination': 1 if inputan["skin_type"]== "Combination" else 0,
        'skin_type_Dry': 1 if inputan["skin_type"]== "Dry" else 0,
        'skin_type_Normal': 1 if inputan["skin_type"]== "Normal" else 0,
        'skin_type_Oily': 1 if inputan["skin_type"]== "Oily" else 0,
    })
pd.DataFrame(data_encoding)

,product_id,age_range_18 and Under,age_range_19 - 24,age_range_25 - 29,age_range_30 - 34,age_range_35 - 39,age_range_40 - 44,age_range_45 and Above,skin_type_Combination,skin_type_Dry,skin_type_Normal,skin_type_Oily
0,259,0,1,0,0,0,0,0,0,1,0,0
1,72429,0,1,0,0,0,0,0,0,1,0,0
2,697,0,1,0,0,0,0,0,0,1,0,0
3,951,0,1,0,0,0,0,0,0,1,0,0
4,606,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
451,98417,0,1,0,0,0,0,0,0,1,0,0
452,101812,0,1,0,0,0,0,0,0,1,0,0
453,101813,0,1,0,0,0,0,0,0,1,0,0
454,98883,0,1,0,0,0,0,0,0,1,0,0
455,103058,0,1,0,0,0,0,0,0,1,0,0

In [4]:
import joblib
import pandas as pd
X = pd.DataFrame(data_encoding)

X

,product_id,age_range_18 and Under,age_range_19 - 24,age_range_25 - 29,age_range_30 - 34,age_range_35 - 39,age_range_40 - 44,age_range_45 and Above,skin_type_Combination,skin_type_Dry,skin_type_Normal,skin_type_Oily
0,259,0,1,0,0,0,0,0,0,1,0,0
1,72429,0,1,0,0,0,0,0,0,1,0,0
2,697,0,1,0,0,0,0,0,0,1,0,0
3,951,0,1,0,0,0,0,0,0,1,0,0
4,606,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
451,98417,0,1,0,0,0,0,0,0,1,0,0
452,101812,0,1,0,0,0,0,0,0,1,0,0
453,101813,0,1,0,0,0,0,0,0,1,0,0
454,98883,0,1,0,0,0,0,0,0,1,0,0
455,103058,0,1,0,0,0,0,0,0,1,0,0

Melakukan prediksi rating

In [5]:
dtr1 = joblib.load(f"models/dtr1/{tag}.pkl")
rating = dtr1.predict(X)

df_rating = X.copy()
df_rating['rating'] = rating
df_rating

,product_id,age_range_18 and Under,age_range_19 - 24,age_range_25 - 29,age_range_30 - 34,age_range_35 - 39,age_range_40 - 44,age_range_45 and Above,skin_type_Combination,skin_type_Dry,skin_type_Normal,skin_type_Oily,rating
0,259,0,1,0,0,0,0,0,0,1,0,0,4.666667
1,72429,0,1,0,0,0,0,0,0,1,0,0,3.700000
2,697,0,1,0,0,0,0,0,0,1,0,0,3.333333
3,951,0,1,0,0,0,0,0,0,1,0,0,3.916667
4,606,0,1,0,0,0,0,0,0,1,0,0,4.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,98417,0,1,0,0,0,0,0,0,1,0,0,5.000000
452,101812,0,1,0,0,0,0,0,0,1,0,0,4.000000
453,101813,0,1,0,0,0,0,0,0,1,0,0,1.000000
454,98883,0,1,0,0,0,0,0,0,1,0,0,5.000000
455,103058,0,1,0,0,0,0,0,0,1,0,0,5.000000

Melakukan prediksi rating text

In [6]:
dtr2 = joblib.load(f"models/dtr2/{tag}.pkl")
rating_text = dtr2.predict(X)

df_rating_text = X.copy()
df_rating_text['rating_text'] = rating_text
df_rating_text

,product_id,age_range_18 and Under,age_range_19 - 24,age_range_25 - 29,age_range_30 - 34,age_range_35 - 39,age_range_40 - 44,age_range_45 and Above,skin_type_Combination,skin_type_Dry,skin_type_Normal,skin_type_Oily,rating_text
0,259,0,1,0,0,0,0,0,0,1,0,0,3.569067
1,72429,0,1,0,0,0,0,0,0,1,0,0,2.960192
2,697,0,1,0,0,0,0,0,0,1,0,0,2.876984
3,951,0,1,0,0,0,0,0,0,1,0,0,2.799603
4,606,0,1,0,0,0,0,0,0,1,0,0,2.744048
...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,98417,0,1,0,0,0,0,0,0,1,0,0,3.839286
452,101812,0,1,0,0,0,0,0,0,1,0,0,2.608773
453,101813,0,1,0,0,0,0,0,0,1,0,0,2.008929
454,98883,0,1,0,0,0,0,0,0,1,0,0,2.023810
455,103058,0,1,0,0,0,0,0,0,1,0,0,3.750000

Melakukan klasifikasi is_recommended

In [8]:
X2 = pd.DataFrame({
    "rating":rating,
    "rating_text":rating_text,
})

svm = joblib.load(f"models/svm/{tag}.pkl")
is_recommended = svm.predict(X2)

df_is_recommended = X2.copy()
df_is_recommended['is_recommended'] = is_recommended
df_is_recommended

       rating  rating_text  is_recommended
0    4.444444     3.110607               1
1    4.666667     3.569067               1
2    4.000000     3.714286               1
3    3.000000     2.576531              -1
4    4.000000     2.576531               1
..        ...          ...             ...
451  5.000000     3.416005               1
452  4.800000     3.071594               1
453  4.000000     2.608773               1
454  1.000000     2.008929              -1
455  5.000000     3.750000               1

[456 rows x 3 columns]

Filter yang direkomendasikan dan hitung rata-rata rating

In [9]:
hasil=data.copy()
for id1, rating1, rating_text1, is_recommended1 in zip(product_id, rating, rating_text, is_recommended):
    if is_recommended1 == -1:
        del hasil[id1]
        continue
    hasil[id1].update({
        'rating':rating1,
        'rating_text':rating_text1,
        'average':(rating1+rating_text1)/2,
        'is_recommended':is_recommended1
    })
pd.DataFrame(hasil.values())

,id,name,price,brand,tag,image,rating,description,category,review_count,rating_text,average,is_recommended
0,235,Ultra Facial Cream,465000.00,Kiehl's,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.444444,Kiehl's Ultra Facial Cream adalah pelembab seh...,Moisturizer (Cream),28,3.110607,3.777526,1
1,259,Concentrated Ginseng Renewing Cream EX,1500000.00,Sulwhasoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.666667,Sulwhasoo Concentrated Ginseng Renewing Cream ...,Moisturizer (Cream),9,3.569067,4.117867,1
2,296,Moisture Surge Extended Thirst Relief,542490.00,CLINIQUE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Clinique Moisture Surge Extended Thirst Relief...,Moisturizer (Cream),9,3.714286,3.857143,1
3,412,Putih Langsat,15000.00,Sariayu,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Sariayu Putih Langsat Body Lotion merupakan lo...,Moisturizer (Cream),2,2.576531,3.288265,1
4,501,Skin Recovery Cream D.E.F.I.,425280.00,Avene,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.500000,Avene Skin Recovery Cream D.E.F.I. adalah krim...,Moisturizer (Cream),3,3.042411,3.271205,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,100368,Multiaction Treatment Cream,149000.00,Skinmurch,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,SKINMURCH Multi Action Treatment Cream adalah ...,Moisturizer (Cream),2,2.995323,3.497662,1
407,101234,Probiotic Water-Oil Balance Essence Cream,145000.00,Metoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,5.000000,METOO Probiotic Water-Oil Balance Essence Crea...,Moisturizer (Cream),3,3.416005,4.208003,1
408,101542,Sensitive Skin Care BiomeRepair TopiCalm Cream,205000.00,LABORE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.800000,LABORE Sensitive Skin Care BiomeRepair TopiCal...,Moisturizer (Cream),5,3.071594,3.935797,1
409,101812,Intense Luminous Barrier Moisturizer,69000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Azarine Intense Luminous Barrier Moisturizer a...,Moisturizer (Cream),4,2.608773,3.304386,1
410,103058,Biome & Barrier Cream,149000.00,MS Glow,cream-1,https://image.femaledaily.com/dyn/360/images/p...,5.000000,<p>MS GLOW Biome &amp; Barrier Cream merupakan...,Moisturizer (Cream),1,3.750000,4.375000,1

Menghitung skor akhir menggunakan wilson score interval

In [11]:
import math
def wilson_score(average,review_count):
    p= average/5
    n= review_count
    z= 1.96
    a= p+z**2/(2*n)
    b= math.sqrt((p*(1-p) + z**2/4*n)/n)
    c= 1 + z**2 /n
    atas= (a+b)/c
    bawah= (a-b)/c

    return (atas+bawah)/2

In [12]:
for i in hasil.keys():
    hasil[i]['final_score']=0 if hasil[i]['review_count']==0 else wilson_score(hasil[i]['average'], hasil[i]['review_count'])*5
pd.DataFrame(hasil.values())

,id,name,price,brand,tag,image,rating,description,category,review_count,rating_text,average,is_recommended,final_score
0,235,Ultra Facial Cream,465000.00,Kiehl's,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.444444,Kiehl's Ultra Facial Cream adalah pelembab seh...,Moisturizer (Cream),28,3.110607,3.777526,1,3.623396
1,259,Concentrated Ginseng Renewing Cream EX,1500000.00,Sulwhasoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.666667,Sulwhasoo Concentrated Ginseng Renewing Cream ...,Moisturizer (Cream),9,3.569067,4.117867,1,3.633877
2,296,Moisture Surge Extended Thirst Relief,542490.00,CLINIQUE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Clinique Moisture Surge Extended Thirst Relief...,Moisturizer (Cream),9,3.714286,3.857143,1,3.451150
3,412,Putih Langsat,15000.00,Sariayu,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Sariayu Putih Langsat Body Lotion merupakan lo...,Moisturizer (Cream),2,2.576531,3.288265,1,2.769880
4,501,Skin Recovery Cream D.E.F.I.,425280.00,Avene,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.500000,Avene Skin Recovery Cream D.E.F.I. adalah krim...,Moisturizer (Cream),3,3.042411,3.271205,1,2.838169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,100368,Multiaction Treatment Cream,149000.00,Skinmurch,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,SKINMURCH Multi Action Treatment Cream adalah ...,Moisturizer (Cream),2,2.995323,3.497662,1,2.841571
407,101234,Probiotic Water-Oil Balance Essence Cream,145000.00,Metoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,5.000000,METOO Probiotic Water-Oil Balance Essence Crea...,Moisturizer (Cream),3,3.416005,4.208003,1,3.248949
408,101542,Sensitive Skin Care BiomeRepair TopiCalm Cream,205000.00,LABORE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.800000,LABORE Sensitive Skin Care BiomeRepair TopiCal...,Moisturizer (Cream),5,3.071594,3.935797,1,3.311955
409,101812,Intense Luminous Barrier Moisturizer,69000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Azarine Intense Luminous Barrier Moisturizer a...,Moisturizer (Cream),4,2.608773,3.304386,1,2.910317
410,103058,Biome & Barrier Cream,149000.00,MS Glow,cream-1,https://image.femaledaily.com/dyn/360/images/p...,5.000000,<p>MS GLOW Biome &amp; Barrier Cream merupakan...,Moisturizer (Cream),1,3.750000,4.375000,1,2.887269

Menampilkan produk yang direkomendasikan dengan menghilangkan produk yang tidak memiliki review dan mengurutkan berdasarkan skor akhir

In [13]:
#hasil_akhir = list(filter(lambda row: row['review_count'] != 0, hasil))
hasil_akhir = [hasil[i] for i in hasil.keys() if hasil[i]['review_count']!= 0]
pd.DataFrame(hasil_akhir)

,id,name,price,brand,tag,image,rating,description,category,review_count,rating_text,average,is_recommended,final_score
0,235,Ultra Facial Cream,465000.00,Kiehl's,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.444444,Kiehl's Ultra Facial Cream adalah pelembab seh...,Moisturizer (Cream),28,3.110607,3.777526,1,3.623396
1,259,Concentrated Ginseng Renewing Cream EX,1500000.00,Sulwhasoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.666667,Sulwhasoo Concentrated Ginseng Renewing Cream ...,Moisturizer (Cream),9,3.569067,4.117867,1,3.633877
2,296,Moisture Surge Extended Thirst Relief,542490.00,CLINIQUE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Clinique Moisture Surge Extended Thirst Relief...,Moisturizer (Cream),9,3.714286,3.857143,1,3.451150
3,412,Putih Langsat,15000.00,Sariayu,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Sariayu Putih Langsat Body Lotion merupakan lo...,Moisturizer (Cream),2,2.576531,3.288265,1,2.769880
4,501,Skin Recovery Cream D.E.F.I.,425280.00,Avene,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.500000,Avene Skin Recovery Cream D.E.F.I. adalah krim...,Moisturizer (Cream),3,3.042411,3.271205,1,2.838169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,100368,Multiaction Treatment Cream,149000.00,Skinmurch,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,SKINMURCH Multi Action Treatment Cream adalah ...,Moisturizer (Cream),2,2.995323,3.497662,1,2.841571
407,101234,Probiotic Water-Oil Balance Essence Cream,145000.00,Metoo,cream-1,https://image.femaledaily.com/dyn/640/images/p...,5.000000,METOO Probiotic Water-Oil Balance Essence Crea...,Moisturizer (Cream),3,3.416005,4.208003,1,3.248949
408,101542,Sensitive Skin Care BiomeRepair TopiCalm Cream,205000.00,LABORE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.800000,LABORE Sensitive Skin Care BiomeRepair TopiCal...,Moisturizer (Cream),5,3.071594,3.935797,1,3.311955
409,101812,Intense Luminous Barrier Moisturizer,69000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,Azarine Intense Luminous Barrier Moisturizer a...,Moisturizer (Cream),4,2.608773,3.304386,1,2.910317
410,103058,Biome & Barrier Cream,149000.00,MS Glow,cream-1,https://image.femaledaily.com/dyn/360/images/p...,5.000000,<p>MS GLOW Biome &amp; Barrier Cream merupakan...,Moisturizer (Cream),1,3.750000,4.375000,1,2.887269

Urutkan berdasarkan final_score tertinggi ke terendah

In [14]:
hasil_akhir.sort(key=lambda row: row['final_score'], reverse=True)
result=pd.DataFrame(hasil_akhir)
pd.DataFrame(result)

,id,name,price,brand,tag,image,rating,description,category,review_count,rating_text,average,is_recommended,final_score
0,66185,C White Night Moisturizer,65000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.803922,C White Perfect Radiance Night Moisturizer ada...,Moisturizer (Cream),51,3.471994,4.137958,1,4.023221
1,94498,Skin Barrier Rehab Crème,85000.00,Dermies,cream-1,https://image.femaledaily.com/dyn/640/images/p...,5.000000,Dermies Skin Barrier Rehab Crème merupakan pel...,Moisturizer (Cream),22,3.480294,4.240147,1,3.981458
2,71836,Day Cream Centella Asiatica,115000.00,NPURE,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.818182,BPOM DAY NA 18190124177 \n\n\nRangkaian CICA D...,Moisturizer (Cream),44,3.389441,4.103812,1,3.975028
3,74402,Ultralight Hydraglow Day Cream,55000.00,Azarine Cosmetic,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.941176,WHITENING MULTIDEFENSE DAY CREAM SPF 30 +++\n#...,Moisturizer (Cream),34,3.247782,4.094479,1,3.932611
4,76547,Antioxidant Night Cream,128000.00,Raiku Beauty,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.761905,Nett Weight : 50g\n\nMengunci serum dan member...,Moisturizer (Cream),21,3.535384,4.148644,1,3.893692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,14732,Energizing Day Cream,52000.00,Himalaya,cream-1,https://image.femaledaily.com/dyn/640/images/p...,2.666667,Himalaya Energizing Day Cream merupakan krim p...,Moisturizer (Cream),1,3.571429,3.119048,1,2.627860
407,2935,Aloe Soothing Night Cream,59000.00,The Body Shop,cream-1,https://image.femaledaily.com/dyn/640/images/p...,3.500000,The Body Shop Aloe Soothing Night Cream dapat ...,Moisturizer (Cream),1,2.678571,3.089286,1,2.621713
408,8712,Royal Jelly + ATP Face Lifting Cream,250000.00,Bio-Essence,cream-1,https://image.femaledaily.com/dyn/640/images/p...,2.857143,Bio-Essence Royal Jelly + ATP Face Lifting Cre...,Moisturizer (Cream),1,3.257486,3.057314,1,2.615110
409,28297,Beta Salic 2,130000.00,chica y chico,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,"Gentle Dead Skin Removal at Night Cream, Conta...",Moisturizer (Cream),1,1.956845,2.978423,1,2.598815
410,77701,Original Wormwood Calming Watery Cream,150000.00,Fraijour,cream-1,https://image.femaledaily.com/dyn/640/images/p...,4.000000,"Ingredients : Purified water, butylene glycol,...",Moisturizer (Cream),1,0.000000,2.000000,1,2.396728